//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBanking.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string UserID { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<decimal> InitialBalance { get; set; }
        public Nullable<decimal> Withdrawal { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public string FundTransferToAccount { get; set; }
    }
}
